# makefile for teststack
# the filename must be either Makefile or makefile
$(CC) = gcc
command:command.o
	$(CC) command.o -o command
command.o:command.c command.h
	$(CC) -c command.c
clean:
	rm *.o command